version: '3.4'

services:
  productmicroservice:
    image: productmicroservice
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      JAVA_OPTS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005,quiet=y
    ports:
      - 8882:8882
      - 5005:5005
