version: '3.4'

services:
  usermicroservice:
    image: usermicroservice
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      JAVA_OPTS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005,quiet=y
    ports:
      - 881:8881
      - 5005:5005
